export const dynamic = 'force-dynamic';
import { NextResponse } from 'next/server';
import { isMock, mockClusters, listClusters, createCluster, namespace as defaultNamespace } from '@/lib/k8s';
import { getGitService } from '@/lib/git';
import { SyncService } from '@/lib/sync';
import { driftReconciler } from '@/lib/gitops/reconciler';
import * as fs from 'fs';

export async function GET(request: Request) {
    if (isMock) return NextResponse.json(mockClusters);

    const { searchParams } = new URL(request.url);
    const ns = searchParams.get('namespace'); // Pass null to listClusters for all namespaces

    try {
        const clusters = await listClusters(ns || undefined);
        console.log(`[/api/clusters] Found ${clusters.length} enriched clusters`);
        return NextResponse.json(clusters);
    } catch (e: any) {
        console.error('[/api/clusters] GET failed:', e);
        return NextResponse.json({ error: String(e) }, { status: 500 });
    }
}

export async function POST(request: Request) {
    try {
        const body = await request.json();
        const ns = body.metadata?.namespace || defaultNamespace;

        const log = (msg: string) => fs.appendFileSync('/tmp/debug.log', `[${new Date().toISOString()}] ${msg}\n`);
        log(`[api/clusters] Creating cluster ${body.metadata?.name} in namespace ${ns}`);

        // 1. Initial Drift check: Don't create if PR is already open
        log(`[api/clusters] Getting git service...`);
        const gitService = await getGitService();
        if (gitService) {
            log(`[api/clusters] Checking for open PRs...`);
            const hasPR = await gitService.hasOpenPR(ns, body.metadata.name);
            log(`[api/clusters] hasPR: ${hasPR}`);
            if (hasPR) {
                return NextResponse.json(
                    { error: 'A PR for this cluster is already pending approval' }, 
                    { status: 409 }
                );
            }
        } else {
            log(`[api/clusters] GitOps not configured, skipping PR check`);
        }

        log(`[api/clusters] Creating cluster in K8s...`);
        // 2. Create in K8s
        const result = await createCluster(ns, body);
        log(`[api/clusters] Created in K8s successfully`);

        // 3. Create PR in Git if enabled
        let prUrl: string | undefined;

        if (gitService) {
            log(`[api/clusters] Generating PR for cluster...`);
            const syncService = new SyncService(gitService);
            try {
                prUrl = await syncService.createPRToGit(
                    ns, 
                    body.metadata.name, 
                    body, 
                    `Automated PR for creating cluster ${body.metadata.name}`,
                    `This PR was automatically generated by CNPG Admin when creating the cluster \`${body.metadata.name}\` in namespace \`${ns}\`.`
                );
                log(`[gitops] Successfully created PR for new cluster ${body.metadata.name}: ${prUrl}`);
            } catch (err: any) {
                log(`[gitops] Failed to create PR for new cluster: ${err.message || err}`);
            }
        }

        log(`[api/clusters] Returning response to client`);
        
        // Asynchronously check drift and update cache
        await driftReconciler.triggerReconciliation();

        return NextResponse.json({ ...result, _prUrl: prUrl });
    } catch (e: any) {
        fs.appendFileSync('/tmp/debug.log', `[${new Date().toISOString()}] [/api/clusters] POST failed: ${e}\n`);
        console.error('[/api/clusters] POST failed:', e);
        return NextResponse.json({ error: String(e) }, { status: 500 });
    }
}
